import React from 'react';
import HeroPage from '../components/hero';
import ContentPage from '../components/content.jsx';
//import './about.css';
function AboutPage(props) {
    return (
        <div>
            <HeroPage title={props.title} />
            <ContentPage>
                <div className="container">
                    <p>
                        Fugiat commodo veniam nostrud incididunt voluptate esse minim et cupidatat proident officia cupidatat tempor et tempor eiusmod velit aliquip in enim qui in laborum ea proident exercitation exercitation.
                        Id anim quis enim proident ut officia consequat ut deserunt consequat et dolore nisi sunt do sint adipisicing duis in duis pariatur est laborum cupidatat excepteur cillum in in consequat fugiat proident eu dolor anim laboris ut adipisicing consectetur laborum eiusmod sint magna ut ad labore nostrud mollit eiusmod do magna eu aute veniam adipisicing nulla duis aute dolor nostrud minim id do qui irure labore proident consectetur ex irure enim amet sed in esse aute ut labore ad nostrud sit sit proident sit duis proident et dolor ut magna mollit nisi sit dolor deserunt irure in ad non proident reprehenderit in irure nostrud amet eiusmod et veniam enim excepteur sint est cillum magna culpa culpa occaecat nostrud non elit in elit in ex officia minim in excepteur in id dolor magna reprehenderit cupidatat amet magna sed ad deserunt aliquip dolor sed cillum elit enim exercitation ut non in aute irure dolore commodo eiusmod ut ut aliquip sed cillum occaecat ex ad cillum eu laborum deserunt in ea mollit.
                        Occaecat fugiat. Duis sunt et minim qui irure ad mollit dolor excepteur ex dolor laborum quis labore. Dolore labore nulla minim ad magna dolore culpa laborum voluptate ut ad ad do consectetur irure dolor laborum dolor cupidatat occaecat proident et mollit eiusmod ea sed nulla exercitation aliqua nulla excepteur cupidatat magna ut laboris. Ut sit aute reprehenderit eiusmod ut sed laborum cupidatat pariatur qui et ad ea ad officia voluptate sit excepteur nisi laboris sit ad aliquip aliquip in laboris aliqua nostrud magna duis minim quis in deserunt cupidatat laboris labore in voluptate aliquip anim ex do dolor esse dolor incididunt irure irure ad exercitation non amet commodo veniam laborum sed veniam et minim adipisicing dolore pariatur sint consectetur amet ut veniam in nisi velit do irure do adipisicing laborum veniam magna adipisicing cillum ut velit eu mollit fugiat excepteur aliquip consectetur laborum dolor sed duis laboris elit pariatur magna proident ullamco enim id dolor dolor in eiusmod tempor mollit in minim nostrud veniam aliqua tempor excepteur sed tempor et laborum ullamco deserunt id sunt elit consectetur aliqua sit sed amet est ut id labore cillum sit qui duis sunt qui et ex est qui anim irure laborum culpa qui quis dolore aliquip in excepteur voluptate do ea adipisicing consectetur laboris laborum proident fugiat officia sed dolor fugiat tempor do adipisicing ex laborum aute duis excepteur adipisicing do sed velit laboris dolor culpa ut dolor aliqua tempor esse id magna in labore cupidatat nulla nostrud excepteur ut esse ex qui dolor est do sunt ex id voluptate voluptate ut quis nostrud amet voluptate veniam pariatur dolore voluptate est ad elit elit est dolore ullamco amet voluptate laborum occaecat in in ut est reprehenderit id esse consectetur est in tempor et excepteur eiusmod ullamco est nulla dolor. Lorem ipsum elit fugiat ea consectetur fugiat qui cillum dolor quis eiusmod et non culpa incididunt dolore non nisi incididunt enim anim commodo incididunt cupidatat minim qui nulla magna cillum adipisicing dolore velit et minim nostrud in consequat ea magna culpa exercitation voluptate laborum culpa aliqua laborum ut elit elit eiusmod dolor dolor ut minim magna sit id sit pariatur ullamco cupidatat sint elit nisi eiusmod dolor cupidatat dolor magna veniam ut quis ut enim non in id dolor consectetur ut mollit sed incididunt ea sint ad irure culpa aliqua aute tempor nulla enim ex cupidatat amet excepteur in sunt anim voluptate tempor et consectetur adipisicing aliquip cupidatat do incididunt tempor in sed fugiat deserunt commodo id ullamco est aute in ut dolore dolore nisi incididunt aliqua excepteur cupidatat nulla culpa enim culpa cillum duis occaecat duis voluptate proident consectetur aute exercitation amet quis.
                    </p>
                </div>
            </ContentPage>
        </div>
    );
}

export default AboutPage;